occupations = [
    "Apologist",
    "Sorcerer-contractor",
    "Stockbroker",
    "Astromycologist",
    "Shoeblack",
    "Armory officer",
    "Surveyor",
    "Straight man",
    "Concierge",
    "Helper",
    "Holo-engineer",
    "Exobiologist",
    "Secretary",
    "Computer expert",
    "Leech",
    "Solicitor",
    "Outlaw",
    "Inspector",
    "Research engineer",
    "Sorcerer",
    "Science officer",
    "Firefighter",
    "Historian",
    "Apprentice",
    "Records officer",
    "Obstetrician",
    "Corner man",
    "Liquidator",
    "Systems engineer",
    "Astronomer",
    "Publicist",
    "Surgical Chancellor",
    "Laborer",
    "Mineralogist",
    "President of the Court",
    "Pastry chef",
    "Exopsychologist",
    "Funkmaster",
    "Information dealer",
    "Oceanographer",
    "Biologist",
    "Scholar",
    "Protocol officer",
    "Senior mission officer",
    "Sector commander",
    "Flight instructor",
    "Drama critic",
    "Ambassador",
    "Gardener",
    "Civilian",
    "Gambler",
    "Fortune teller",
    "Missionary",
    "Assistant",
    "Aquanaut",
    "Witch",
    "Town marshal",
    "Analyst",
    "Truant officer",
    "Candy striper",
    "Gunner",
    "Geological technician",
    "Doctor",
    "Quarterback",
    "Flight officer",
    "Prospector",
    "Logistics officer",
    "Net-girl",
    "Zoologist",
    "Samurai",
    "Xenologist",
    "Meteorologist",
    "Guard",
    "Junk dealer",
    "Translator",
    "Prosecutor",
    "Consultant",
    "Farm boy",
    "Ordnance officer",
    "Costume designer",
    "Attendant",
    "Sculptor",
    "Astrotheorist",
    "Plumber",
    "Shopkeeper",
    "Weather coordinator",
    "Lab technician",
    "Maid",
    "Field docent",
    "Journalist",
    "Negotiator",
    "Human cannonball",
    "Merchant",
    "Pilot",
    "Orderly",
    "Field supervisor",
    "Technician",
    "Accountant",
    "Scientific advisor",
    "Bureaucrat",
    "Phaser crew",
    "Promoter",
    "Cyberneticist",
    "Athlete",
    "Internship",
    "Medical repair drone",
    "Midwife",
    "Spokesman",
    "Dockmaster",
    "EPS control specialist",
    "Thanatologist",
    "Critic",
    "Thermologist",
    "Chancellor of the Klingon High Council",
    "Delivery man",
    "Highway patrolman",
    "Financial assistant",
    "Politician",
    "Criminal",
    "Detective",
    "Preacher",
    "Potter",
    "Chaperone",
    "Parking enforcement officer",
    "Servant",
    "Weapons specialist",
    "Assayer",
    "Contractor",
    "Minister",
    "Entertainment director",
    "Chief of Medicine",
    "Grand Nagus",
    "Stellar physicist",
    "Efficiency Monitor",
    "Marksman",
    "Mutineer",
    "Borg drone",
    "Looter",
    "Gun runner",
    "GhojmoK",
    "Attach\u00e9",
    "Cryptologist",
    "Xenoanthropologist",
    "Hustler",
    "Superintendent",
    "Customs inspector",
    "President",
    "Chemist",
    "Military advisor",
    "Mission specialist",
    "Programmer",
    "Hygienist",
    "Juggler",
    "Chief medical officer",
    "Holophotographer",
    "Neurosurgeon",
    "Archaeology and anthropology officer",
    "Warlock",
    "Monk",
    "Minstrel",
    "Janitor",
    "First contact specialist",
    "Poet",
    "Medical trustee",
    "Judge",
    "Geisha",
    "Physician",
    "Dance instructor",
    "Archon",
    "Escape artist",
    "Waste processor",
    "Police officer",
    "Garbage man",
    "Inventor",
    "Art critic",
    "Biomolecular physiologist",
    "Test taster",
    "Maintenance Engineer, First Class",
    "Orion slave girl",
    "Designer",
    "Gladiator",
    "Observer",
    "Job placement",
    "Caterer",
    "Assassin",
    "Professor",
    "Warp field theorist",
    "Chief Archon",
    "Gangster",
    "Psychologist",
    "Soldier boy",
    "Pioneer",
    "Storyteller",
    "Nestor",
    "Prophet",
    "Financier",
    "Bodyguard",
    "Butler",
    "Driver",
    "Gunslinger",
    "Bricklayer",
    "Mandarin bailiff",
    "Parking lot attendant",
    "Botanical surveyor",
    "Socialite",
    "Communications officer",
    "Teacher",
    "Administrator",
    "Sea rancher",
    "Trill initiate",
    "Mercenary",
    "Titanium smith",
    "Deputy",
    "Medical supervisor",
    "Assistant manager",
    "Dock worker",
    "Clerk",
    "Pitcher",
    "Cowboy",
    "Soldier",
    "Personnel officer",
    "Mail carrier",
    "Housekeeper",
    "Comfort woman",
    "Valet",
    "Psychiatrist",
    "Medic",
    "Cutter",
    "Orator",
    "Collaborator",
    "Mechanic",
    "Assistant Manager of Policy and Clientele",
    "Robber",
    "Archaeologist",
    "Anthropologist",
    "Communications master",
    "Healer",
    "Singer",
    "Sailor",
    "Pirate",
    "Puppeteer",
    "Therapist",
    "Agent",
    "Chef",
    "Sanitation engineer",
    "Magician",
    "Miner",
    "Businessman",
    "Pathologist",
    "Transporter chief",
    "Exozoologist",
    "Commissioner",
    "Priest",
    "Assistant communications officer",
    "Biosphere designer",
    "Chirurgeon",
    "Sniper",
    "Breeder",
    "Medicine man",
    "Hostage",
    "Prisoner",
    "Bellboy",
    "Courier",
    "Tragedian",
    "Race coordinator",
    "Con artist",
    "Technical clerk",
    "Crusader",
    "Wizard",
    "Doctor of Medicine",
    "Welder",
    "Apothecary",
    "Emergency medical technician",
    "Student",
    "Geological engineer",
    "Medical assistant",
    "Patroller",
    "Vulcan master",
    "Messenger",
    "Station manager",
    "Orbital engineer",
    "Food taster",
    "Explorer",
    "Medical examiner",
    "Judge Advocate General",
    "Orthodontist",
    "Shepherd",
    "Emperor",
    "Core laborer",
    "Aerospace engineer",
    "Personal assistant",
    "Cavalry",
    "Director",
    "Drug broker",
    "Eliminator",
    "Undertaker",
    "Sheriff",
    "Builder",
    "Cultural observer",
    "Physicist",
    "Butcher",
    "Ombudsman",
    "Molecular paleontologist",
    "Hunter",
    "Arms dealer",
    "Masseur",
    "Legal guardian",
    "Duty personnel",
    "Traitor",
    "Stellar cartographer",
    "Plasma specialist",
    "Car salesman",
    "Field hand",
    "Maintenance engineer",
    "Renegade",
    "Executioner",
    "Oyster pirate",
    "Flight Surgeon",
    "Traveler",
    "Dealer",
    "Blacksmith",
    "Extremist",
    "Tracer",
    "Strategist",
    "Steward",
    "Busboy",
    "Engineering physicist",
    "First Clerk",
    "Statesman",
    "Swordsman",
    "Chief of surgery",
    "Saturnius harem girl",
    "High advisor",
    "Theologian",
    "Weatherman",
    "Rescuer",
    "Surgeon",
    "Playwright",
    "Resistance fighter",
    "Writer",
    "Sociologist",
    "Terraformer",
    "Cargo handler",
    "Moon shuttle conductor",
    "Nurse maid",
    "Anarchist",
    "Manager",
    "Hematologist",
    "Wet nurse",
    "Coach",
    "Swashbuckler",
    "Fisherman",
    "Guest lecturer",
    "Geneticist",
    "Liaison",
    "Groundskeeper",
    "Arbiter",
    "Cobbler",
    "Defector",
    "Librarian",
    "Croupier",
    "Conservator",
    "Lockpick",
    "Construction work",
    "Inquisitor",
    "Craftsman",
    "Warp field engineer",
    "US Marshal",
    "Boxer",
    "Matchmaker",
    "Smuggler",
    "Advocate",
    "Farmer",
    "Warrior",
    "Tactician",
    "Personnel director",
    "Guard",
    "Ethnobotanist",
    "Referee",
    "Parole officer",
    "Council Regent",
    "File clerk",
    "Iron weaver",
    "Social worker",
    "Informant",
    "Broker",
    "Junior science officer",
    "Electronics engineer",
    "People doctor",
    "Alcoholic",
    "Veterinarian",
    "Diagnostic and Repair Technician, Junior Grade",
    "Tour guide",
    "Manicurist",
    "Delegate",
    "Supervisor",
    "Grocer",
    "Sensor technician",
    "Court buffoon",
    "Waiter",
    "Baker",
    "Umpire",
    "Lawyer",
    "Bartender",
    "Dishwasher",
    "Rider",
    "Zookeeper",
    "Deep sea diver",
    "Editor",
    "Barber",
    "Inspector general",
    "Communications clerk",
    "Junior adjutant",
    "Shrink",
    "Henchman",
    "Knight",
    "Subspace theoretician",
    "Bookkeeper",
    "Server",
    "Transport attendant",
    "Court recorder",
    "Agricultural engineer",
    "Dancer",
    "Community leader",
    "Decorator",
    "Technical aide",
    "Chairman",
    "Plastic surgeon",
    "Temporal agent",
    "Nun",
    "Entomologist",
    "Double agent",
    "Stage crew",
    "Pit boss",
    "Exterminator",
    "Investigator",
    "Court reporter",
    "Aide-de-camp",
    "High priestess",
    "Thief",
    "Waste controller",
    "Runner",
    "Marine biologist",
    "Screw",
    "Tactical officer",
    "Quartermaster",
    "Philanthropist",
    "Author",
    "Intelligence officer",
    "Record keeper",
    "Cleric",
    "Plant manager",
    "Governess",
    "Substitute teacher",
    "Duty engineer",
    "Clothier",
    "Duty officer",
    "Curator",
    "Law enforcement officer",
    "Artisan",
    "Astrophysicist",
    "Medical technician",
    "Torpedo technician",
    "Mining engineer",
    "Homemaker",
    "Robotics scientist",
    "Science specialist",
    "Stockboy",
    "Child specialist",
    "Emergency Medical Hologram Replacement Program",
    "Reporter",
    "Warp field specialist",
    "Asteroid locator",
    "Constable",
    "Warden",
    "Conference coordinator",
    "Engineer's assistant",
    "Restaurateur",
    "Diplomat",
    "Legal intercessor",
    "Engineering advisor",
    "Snake oil salesman",
    "Geologist",
    "Mediator",
    "Pilgrim",
    "Archivist",
    "Animal trainer",
    "Gravedigger",
    "Principal",
    "Coroner",
    "Quantum theorist",
    "Mistress",
    "Yard superintendent",
    "Neuro-specialist",
    "Huckster",
    "Chief scientist",
    "Food critic",
    "Drifter",
    "Honatta",
    "Prizefighter",
    "Metallurgical scientist",
    "Bounty hunter",
    "Neurologist",
]
